# Introduction to Pytorch

Partly based on https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/tutorial2/Introduction_to_PyTorch.html

## What is Pytorch?

- Numpy
- ... with GPU support
- Automatic differentiation engine
- Library for neural network components
- Library for optimization methods

## Parallels between Pytorch and Numpy

If you install a current version of pytorch, you should have version `2.5`. 

In [1]:
import torch

print(torch.__version__)

2.1.1


In [2]:
import numpy as np

The equivalent to the numpy array is the [torch Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor).

In [3]:
data = [[1, 2], [3, 4]]

x_np = np.array(data)
x = torch.Tensor(data)

print(x_np)
print(x)

[[1 2]
 [3 4]]
tensor([[1., 2.],
        [3., 4.]])


Many tensor creation operations have the same name like numpy:

In [4]:
n_rows = 5
n_cols = 10

print(torch.zeros((n_rows, n_cols)))
print(np.zeros((n_rows, n_cols)))

torch.ones
np.ones

torch.ones_like
np.ones_like

#...


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<function ones_like at 0x0000022CCCBBC7F0>

Indexing works the same way.

In [5]:
x_np = np.arange(24).reshape(4, 6)
print(x_np)

x = torch.arange(24).reshape(4, 6)
print(x)

print(x_np[1:5:2, :])
print(x[1:5:2, :])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]
tensor([[ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]])


... but there are some differences:

In [6]:
print(x_np[0,0], type(x_np[0, 0]))

print(x[0, 0], type(x[0, 0]))
print(x[0, 0].item(), type(x[0, 0].item()))

0 <class 'numpy.int32'>
tensor(0) <class 'torch.Tensor'>
0 <class 'int'>


We can get the shape the same way.

In [7]:
print(x_np.shape)
print(x.shape)

print(x.size(dim=1))
print(x.shape[1])

(4, 6)
torch.Size([4, 6])
6
6


You can create a tensor from an array and an array from a tensor.

In [8]:
x = torch.from_numpy(x_np)
print(x)

x_np[0,0] = -1000

print(x_np)
# what else has changed?
print(x)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]], dtype=torch.int32)
[[-1000     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]]
tensor([[-1000,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23]], dtype=torch.int32)


In [9]:
print(x.numpy())

[[-1000     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]]


Operations work just like numpy:

In [10]:
x = torch.ones((4,4))

print(x @ x)  # matrix multiplication
x + x

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

Some additional in-place operations that save memory. Marked with `_` at the end of the operation.

In [11]:
x + x  # creates a new tensor, x will remain as is
print(x)
x.add_(x)  # in place, x will be modified
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


## GPU support

A Graphic Processing Unit (GPU) can be thought of as a processor with _many_ cores (think thousands), which however are limited in their instruction set.
[Kevin Krewell, 2009](https://blogs.nvidia.com/blog/2009/12/16/whats-the-difference-between-a-cpu-and-a-gpu/) gives the following comparison:
| CPU | GPU |
| -------- | -------- |
| Central Processing Unit | Graphics Processing Unit |
| Several cores | Many cores |
| Low latency | High throughput |
| Good for serial processing | Good for parallel processing |
| Can do a handful of operations at once | Can do thousands of operations at once |

For example, the recent Nvidia H100 GPU has 456 "Tensor Cores", which are specifically designed for machine learning workloads.

In deep learning, highly parallelizable linear algebra operations are everywhere, which makes a GPU a suitable accelerator for deep learning tasks.
Speedup can be up to two magnitudes.

*To use GPUs with Pytorch, you need to install the correct version.*
* with CUDA for Nvidia GPUs
* with ROCm for AMD GPUs

CUDA is software from NVIDIA to make use of GPUs easier (for developers, we do not directly interface with it).
Nvidia dominates the market, so typically we move data to a "CUDA" device to use GPU.


AMD has similar software (ROCm), though less mature. 
You can install pytorch with ROCm support, but you still move data to GPU via a "cuda" device.

In [12]:
print(torch.cuda.is_available())  # to check whether pytorch was compiled with GPU support and whether a GPU is available

False


In [13]:
device = torch.device("cpu")
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

device

device(type='cpu')

How can we use this with tensors?

In [14]:
x = torch.arange(5, device=device)

x = torch.arange(5).to(device)

print(x.device)

cpu


Operations require both tensors to be on the same device:

In [15]:
x = torch.arange(5, device=torch.device("cuda"))

y = torch.arange(5, device=torch.device("cpu"))

x + y


AssertionError: Torch not compiled with CUDA enabled

## What is Pytorch?

- Numpy [Done]
- ... with GPU support [Done]
- Automatic differentiation engine
- Library for neural network components
- Library for optimization methods

## Example: Linear Regression

We are given inputs $x_i \in \R^p$ and targets $y_i \in \R$ for $i \in {1, \dots, n}$.

For example: $x_i$ consists of measurements of temperature, humidity, rainfall, etc., and $y_i$ is the amount of ice cream sold at a particular shop.

A linear regression model models the sales as a function of the form:
$$y_i = f(x_i, w) = w_o + \sum_{k=1}^p w_k x_{ik}$$
with $w = [w_0, \dots, w_p]$ parameters.

How to choose the parameters (make the predictions fit the real data)?

Define an error function $$E(w)= \sum_{i=1}^n (f(x_i, w) - y_i)^2$$ and minimize it.

In [18]:
import matplotlib.pyplot as plt

(Synthetic) ground truth data:

In [ ]:
torch.manual_seed(123)

x = 10 + 20 * torch.rand((30,)).to(dtype=torch.float)
x = x.reshape(-1, 1)
y = 2.7 * x + 2 * torch.randn_like(x) + 5

# Always: visualize data!
plt.scatter(x, y)

Linear regression implementation (numpy):

In [ ]:
class LinearRegression():
    def __init__(self) -> None:
        self.w = None

    def _add_constant(self, X: np.ndarray) -> np.ndarray:
        """Add a constant column to a matrix

        Args:
            X (np.ndarray): Original data matrix

        Returns:
            np.ndarray: Original data matrix with concatenated column of all ones.
        """
        return np.hstack((X, np.ones((len(X), 1))))

    def fit(self, X: np.ndarray, y: np.ndarray) -> None:
        """Fit the parameters of the model to the data

        Args:
            X (np.ndarray): features
            y (np.ndarray): targets
        """
        X = self._add_constant(X)
        self.w = np.linalg.inv(X.T @ X) @ X.T @ y  # there is also np.linalg.pinv

    def predict(self, X: np.ndarray) -> np.ndarray:
        """Use parameters to predict values

        Args:
            X (np.ndarray): features

        Returns:
            np.ndarray: predicted targets
        """
        X = self._add_constant(X)
        return X @ self.w

X = x.numpy()
model = LinearRegression()
model.fit(X, y.numpy())
preds = model.predict(X)

plt.scatter(x, y)

sort_idx = x.flatten().argsort()
plt.plot(x[sort_idx,0], preds[sort_idx,0], color="red", label="Predictions")
plt.legend()

model.w

We could solve this here, but in general:
- Calculating the gradient manually is cumbersome
- Not all equation systems have analytical solutions

Hence, Pytorch helps us by
- computing gradients automatically
- and giving us the tools to optimize functions numerically.

### Automatic Differentiation

Pytorch keeps track of the so-called "computation graph" (We will come back to this in a few weeks).
This graph records all the operations done on (specific) tensors, thus traces the function that the tensors are used in.

In [ ]:
v  = torch.ones(3)
print(v.requires_grad)

v  = torch.ones(3, requires_grad=True)
print(v.requires_grad)


Let's define a simple function: $c (v) = \sum_i (v_i-2)^2$

In [ ]:
a = v - 2
b = a**2
c = b.sum()

print(c)
print(b)
print(a)

We calculate the gradients $\nabla_v c = [\partial c/\partial v_1, \dots]^T$ by calling `.backward()` on `c`.

In [ ]:
c.backward()

Now the `.grad` attribute is populated with the gradient values.

In [ ]:
print(v.grad)

### Numerical Optimization

How does having the gradient help us in any way?

_Gradient descent_ (GD) is a method to optimize differentiable functions (details in the coming weeks).
All GD needs are the gradient values of the parameters, and access to the parameters itself. We have both with pytorch.

In [ ]:
import torch.nn as nn  # the part of torch with all neural network components (and loss functions)

# automatically registers parameters of layers inside it as trainable (i.e., requires_grad=True)
# needs to methods: __init__ to describe what components the NN consists of, and forward to describe how they interact
class LinearRegressionPytorch(nn.Module):
    def __init__(self, n_features):
        super().__init__()

        self.linear = nn.Linear(n_features, 1, bias=True)  # Ax+b

    def forward(self, x):
        return self.linear(x)

model_pt = LinearRegressionPytorch(x.size(-1))
for param_name, param in model_pt.named_parameters():
    print(param_name, param)

In [ ]:
model_pt.linear.weight

In [29]:
preds = model_pt(x)

In [30]:
preds.sum().backward()


In [ ]:

model_pt.linear.weight.grad


Whenever you use the model, the operations are recorded, so that the gradient can be computed later.
Some operations should not be tracked, e.g., evaluation on a validation data set.
Also, the recording is not free: it takes up memory.

In [ ]:
model_pt = LinearRegressionPytorch(x.size(-1))

# the context manager temporarily turns off recording of operations
with torch.no_grad():
    out = model_pt(x)
    loss = out.sum()
    # loss.backward()
print(model_pt.linear.weight.grad)

out = model_pt(x)
loss = out.sum()
loss.backward()
print(model_pt.linear.weight.grad)


# You can use the function decorator for functions that should influence gradients
@torch.no_grad()
def eval(model, x_val, y_val):
    pred = model(x_val)
    return (pred - y_val).sum()


A minimal training loop looks like this:

In [ ]:
model_pt = LinearRegressionPytorch(x.size(-1))

preds_epochs = []

optimizer = torch.optim.SGD(model_pt.parameters(), lr=5e-4)  # register the parameters with the optimization method
loss_func = nn.MSELoss()
n_epochs = 20
for epoch in range(n_epochs):
    output = model_pt(x)  # Step 1: forward pass
    loss = loss_func(output, y)  # Step 2: compute loss
    optimizer.zero_grad()  # Step 3 : .grad attributes = 0
    loss.backward()  # Step 4: Compute gradients (populate .grad attributes again)
    optimizer.step()  # Step 5: optimization step

    print(f"{epoch=}: loss={loss.item()}")
    preds_epochs.append(output.detach())

In [ ]:
import matplotlib as mpl

fig, ax = plt.subplots()
cmap = mpl.colormaps.get_cmap("viridis")
label_every_n_epoch = 3
ax.scatter(x.view(-1), y.view(-1), color="blue")
for epoch, preds in enumerate(preds_epochs):
    sort_idx = x.flatten().argsort()
    if epoch % label_every_n_epoch == 0:
        kwargs = dict(
            color=cmap(epoch / len(preds_epochs)), label=f"Predictions ({epoch=})"
        )
    else:
        kwargs = dict(
            color=cmap(epoch / len(preds_epochs))
        )

    ax.plot(
        x[sort_idx, 0], preds[sort_idx, 0], **kwargs,
    )
ax.legend()


There is more, which we will cover in the upcoming weeks.